# Generated by Django 4.0.5 on 2022-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vacany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_img', models.ImageField(upload_to='pics')),
                ('salary', models.IntegerField()),
                ('job_type', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=100)),
                ('job_level', models.CharField(max_length=100)),
                ('vacany_number', models.IntegerField()),
                ('educationlevel', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
    ]
