# Generated by Django 4.0.5 on 2022-06-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_message_delete_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
            ],
        ),
    ]
