# Generated by Django 4.0.5 on 2022-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactus_delete_contactmessage_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='sotrecarasoul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),

    ]
