# Generated by Django 4.0.5 on 2022-06-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sotrecarasoul_delete_contactmessage_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptopinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('processor', models.CharField(max_length=100)),
                ('graphics', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('screen', models.CharField(max_length=100)),
            ],
        ),
    ]
