# Generated by Django 4.0.5 on 2022-06-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_laptopinfo_delete_contactmessage_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptopbrandname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
